services:
  jenkins:
    container_name: jenkins
    restart: always
    image: jenkins/jenkins:latest
    ports:
      - 8082:8080
    volumes:
      - ${SETTING_PATH}/jenkins_home:/var/jenkins_home

  jenkins-agent:
    container_name: jenkins-agent
    image: jenkins/ssh-agent:alpine-jdk21
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${SSH_AGENT_KEY}
    ports:
      - 4444:22
    restart: always